service: dictbot

frameworkVersion: ">=1.4.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  environment: ${file(env.yml)}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
       - "lex:PostContent"
       - "lex:PostText"
      Resource: "*"

package:
  exclude:
    - '.*'
    - '*.iml'
    - 'env.yml*'
    - 'data/*'
    - 'utils/*'

functions:
  facebook-get:
    handler: facebook.get
    description: GET handler for verification
    memorySize: 128
    timeout: 5
    events:
      - http: GET /
  facebook-post:
    handler: facebook.post
    description: POST handler for receiving and sending messages
    memorySize: 128
    timeout: 35
    events:
      - http: POST /
  lex-handler:
    handler: lex.handler
    description: Lex handler
    memorySize: 128
    timeout: 30
