Resources:
  PollyCacheBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
Outputs:
  PollyCacheBucketName:
    Description: S3 Polly cache bucket
    Value: !Ref PollyCacheBucket
    Export:
      Name: 'dictbot-s3-polly-cache-bucket-name'
  PollyCacheBucketArn:
    Description: S3 Polly cache bucket ARN
    Value: !GetAtt [PollyCacheBucket, Arn]
    Export:
      Name: 'dictbot-s3-polly-cache-bucket-arn'
